# We have a conf and classes directory, add to BBPATH
BBPATH .= ":${LAYERDIR}"

# We have recipes-* directories, add to BBFILES
BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
            ${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "meta-sg2044"
BBFILE_PATTERN_meta-sg2044 = "^${LAYERDIR}/"
BBFILE_PRIORITY_meta-sg2044 = "6"

LAYERDEPENDS_meta-sg2044 = "core"
LAYERSERIES_COMPAT_meta-sg2044 = "kirkstone langdale"
