# We have a conf and classes directory, add to BBPATH
BBPATH .= ":${LAYERDIR}"

# We have recipes-* directories, add to BBFILES
BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
            ${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "meta-sophgo-sra1"
BBFILE_PATTERN_meta-sophgo-sra1 = "^${LAYERDIR}/"
BBFILE_PRIORITY_meta-sophgo-sra1 = "6"

LAYERDEPENDS_meta-sophgo-sra1 = "core"
LAYERSERIES_COMPAT_meta-sophgo-sra1 = "kirkstone langdale"
